config/routes.rb
Rails.application.routes.draw do
  authenticate do
    get 'admin', to: redirect('admin/enterprise')
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin' 
  end

  get '/:locale' => 'promos#index'
  devise_for :users

  scope "(:locale)", locale: /en|ru|uk/ do
    root 'promos#index'
    resources :enterprises, :events, :promos
    resources :vacancies do
      member do
        post 'send_cv'
      end
    end
  end

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base

  belongs_to :enterprise
  belongs_to :job_category
  belongs_to :job_type #Full time, Part time ...
  belongs_to :currency

  validates :enterprise_id,
            :job_category_id,
            :job_type_id,
            :currency_id,
            :name,
            :open_date,
            :close_date,
            :presence => true
  validates :name, length: { in: 2...200 }
  validates :salary, :enterprise_id, :job_category_id, :job_type_id,numericality: { only_integer: true }

  self.per_page = 5

  def expired?
    unless self.close_date.to_s.blank?
      return (self.close_date - DateTime.now.to_date).to_i < 0
    else
      return false
    end
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :find_item, only: [:show, :send_cv]
  include DataFile
  @@resume_white_list = %w(doc docx pdf)

  def index
    if params[:cat].present?
      @vacancies = Vacancy.where(:job_category_id => params[:cat]).order(:created_at => :desc).paginate(:page => params[:page])
    else
      @vacancies = Vacancy.order(:created_at => :desc).paginate(:page => params[:page])
    end
    @categories = JobCategory.all
  end

  def send_cv
    if validate_resume_form?
      #send_mail_to_user
      #send_mail_to_enterprise
    end
    redirect_to action: :show
  end

  private
  def validate_resume_form?
    result = false
    if validate_resume_params
      if validate_resume_file params[:attachment]
        flash['success'] = "Thank you for your resume. We will contact you ASAP."
        result = true
      else
        flash['danger'] = "Your file must be in format \"#{@@resume_white_list.to_sentence(last_word_connector: ' or ')}\""
      end
    else
      flash['danger'] = "Not all required fields are filled."
    end
    return result
  end

  private
  def validate_resume_file file
    @@resume_white_list.include? DataFile.get_file_extension file
  end

  private
  def validate_resume_params
    !params[:attachment].nil? && params[:name].present? && params[:email].present?
  end

  def find_item
    @vacancy = Vacancy.find(params[:id])
  end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
  def print_date open_date, close_date, actual_class
    return "
      <span class=\"label label-#{actual_class}\">#{open_date}</span> -
      <span class=\"label label-#{actual_class}\">#{close_date}</span>".html_safe
  end
end

app/views/vacancies/_item.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <div class="well well-sm text-center">
            <%= link_to image_tag(item.enterprise.picture_url, size: '250', class: "img-thumbnail"), item.enterprise %>
        </div>
      </div>
      <div class="col-md-8">
        <div class="well">
            <%= print_alert 'danger', "#{t 'This job is no longer actual'}. #{t 'Expired on'} #{item.close_date}" if item.expired? %>
            <h3><%= link_to item.name, item %></h3>
            <p><%=t 'expiration' %>: <%= print_date(item.open_date, item.close_date, item.expired? ? 'default' : 'success') %></p>
            <p><%=t 'company' %>: <%= link_to item.enterprise.name, item.enterprise %></p>
            <%= "<p>#{t 'phone'}: #{item.enterprise.phone}</p>".html_safe unless item.enterprise.phone.blank? %>
            <%= "<p>#{t 'job type'}: #{t item.job_type.name.to_s}</p>".html_safe unless item.job_type.blank? %>
            <%= "<p>email: #{item.enterprise.email}</p>".html_safe unless item.enterprise.email.blank? %>
            <%= "<p>#{t 'salary'}: #{item.salary}</p>".html_safe unless item.salary.blank? %>
        </div>
      </div>
    </div>
    <% unless item.description.empty? %>
        <div class="well">
          <%= truncate(item.description, :length => 300) %>
          <%= link_to (t 'read more'), item %>
        </div>
    <% end %>
  </div>
</div>

app/views/vacancies/index.html.erb
<div class="page-header">
  <h1><%=t "#{controller_name}" %>
    <small><%= action_name %></small>
  </h1>
</div>
<div class="body_panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-8">
        <% unless @vacancies.blank? %>
            <% @vacancies.each do |vacancy| %>
                <%= render "item", {item: vacancy} %>
            <% end %>
        <% else %>
            <div><%=t "no vacancies yet" %></div>
        <% end %>
      </div>
      <div class="col-md-4">
        <% unless @categories.blank? %>
            <div class="list-group">
              <% @categories.each do |category| %>
                  <%= link_to "#{t category.name.to_s}<span class=\"badge\">#{category.vacancies.size}</span>".html_safe, vacancies_path(:cat => category.id), class: "list-group-item#{category.id == params[:cat].to_i ? ' active' : ''}" %>
              <% end %>
              <%= link_to "#{t 'All'}<span class=\"badge\">#{Vacancy.all.size}</span>".html_safe, vacancies_path, class: "list-group-item#{!params[:cat].present? ? ' active' : ''}" %>
            </div>
        <% else %>
            <div><%=t  'categories are empty'%></div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="text-center"><%= will_paginate @vacancies, renderer: BootstrapPagination::Rails %></div>
</div>

app/views/vacancies/show.html.erb
<div class="page-header">
  <h1><%=t controller_name %>
    <small><%= action_name %></small>
  </h1>
</div>

<div class="body_panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col col-md-4 col-lg-3">
        <div class="well">
          <%= link_to image_tag(@vacancy.enterprise.picture_url, :class => 'img-thumbnail', :size => '250'), @vacancy.enterprise %>
        </div>
      </div>
      <div class="col col-md-8 col-lg-9">
        <div class="well">
          <%= print_alert 'danger', "#{t 'This job is no longer actual'}. #{t 'Expired on'} #{@vacancy.close_date}" if @vacancy.expired? %>
          <h3><%= @vacancy.name %></h3>
          <ul class="list-group">
            <li class="list-group-item"><%= t 'expiration' %>: <%= print_date(@vacancy.open_date, @vacancy.close_date, @vacancy.expired? ? 'default' : 'success') %></li>
            <li class="list-group-item"><%= t 'company' %>: <%= link_to @vacancy.enterprise.name, @vacancy.enterprise %></li>
            <%= "<li class=\"list-group-item\">#{t 'category'}: #{@vacancy.job_category.name}</li>".html_safe unless @vacancy.job_category.blank? %>
            <%= "<li class=\"list-group-item\">#{t 'phone'}: #{@vacancy.enterprise.phone}</li>".html_safe unless @vacancy.enterprise.phone.blank? %>
            <%= "<li class=\"list-group-item\">Email: #{@vacancy.enterprise.email}</li>".html_safe unless @vacancy.enterprise.email.blank? %>
            <%= "<li class=\"list-group-item\">#{t 'job type'}: #{@vacancy.job_type.name}</li>".html_safe unless @vacancy.job_type.blank? %>
            <%= "<li class=\"list-group-item\">#{t 'salary'}: #{@vacancy.salary} #{@vacancy.currency.name}</p>".html_safe unless @vacancy.salary.blank? %>
            <%= "<li class=\"list-group-item\">#{t 'location'}: #{@vacancy.location}</li>".html_safe unless @vacancy.location.blank? %>
            <%= "<li class=\"list-group-item\">#{t 'education'}: #{@vacancy.education}</li>".html_safe unless @vacancy.education.blank? %>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col col-md-6">
        <% unless @vacancy.description.blank? %>
            <div class="well">
              <h3><%= t 'Job description' %>:</h3>
              <%= @vacancy.description %>
            </div>
        <% end %>
      </div>
      <div class="col col-md-6">
        <div class="well">
          <h3>Your resume:</h3>
          <h5>If you are interested in this position, please send us your CV (in format <b>pdf, doc, docx</b>) and we will contact you ASAP</h5>
          <%= form_tag(send_cv_vacancy_path, :multipart => true, :method => 'post') do %>
              <div class="form-group no-margins">
                <%= label_tag :name %>
                <%= text_field_tag :name, '', {class: 'form-control', placeholder: 'Enter your name'} %>
              </div>
              <div class="form-group no-margins">
                <%= label_tag :email %>
                <%= email_field_tag :email, '', {class: 'form-control', placeholder: 'Enter your email'} %>
              </div>
              <div class="form-group no-margins">
                <%= label_tag :attachment %>
                <%= file_field_tag :attachment, multiple: false %>
              </div>
              <%= submit_tag 'Send resume' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>