config/routes.rb
Rails.application.routes.draw do
  authenticate do
    get 'admin', to: redirect('admin/enterprise')
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin' 
  end

  get '/:locale' => 'promos#index'
  devise_for :users

  scope "(:locale)", locale: /en|ru|uk/ do
    root 'promos#index'
    resources :enterprises, :events, :promos
    resources :vacancies do
      member do
        post 'send_cv'
      end
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  mount_uploader :image, EventImageUploader
   # belongs_to :event_category
  has_many :event_times, -> { order(time: :asc) }, dependent: :delete_all
  belongs_to :enterprise
  validates :name,:enterprise_id, :description, :start_date, :final_date, presence: true, allow_blank: false
  validates :name, length: { in: 2...200 }
  validates :enterprise_id, numericality: { only_integer: true }
  validates :price, numericality: true
  validate :final_date_must_be_after_start_date
  validate :date_must_be_in_future, on: :create

  self.per_page = 5

  scope :order_by_post_date, ->{ order(created_at: :desc) }
  scope :actual, -> { where('final_date >= ?', Date.today) }
  scope :start_date_filter, -> (filter_start_date) { where('start_date <= ?', filter_start_date).where('final_date >= ?', filter_start_date) }
  scope :end_date_filter, -> (filter_end_date) { where('final_date <= ?', filter_end_date) }
  scope :include_connected_stuff, -> { includes(:event_times,:enterprise) }
 def duration
   "#{start_date}*#{final_date}".gsub('-','.').gsub('*',' - ')
 end

  def final_date_must_be_after_start_date
    if start_date > final_date
      errors.add(:final_date, 'should be AFTER start date')
    end
  end

  def date_must_be_in_future
    if start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end
  private



end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :find_item, only: [:edit, :update, :destroy, :show]

  def index
    if params[:filter_start_date]
    @events= Event.include_connected_stuff.start_date_filter(params[:filter_start_date]).order_by_post_date.paginate(:page => params[:page])

    elsif params[:filter_start_date] && [:filter_end_date]
      @events= Event.include_connected_stuff.start_date_filter(params[:filter_start_date]).end_date_filter(params[:filter_end_date]).order_by_post_date.paginate(:page => params[:page])

    else
      @events = Event.include_connected_stuff.actual.order_by_post_date.paginate(:page => params[:page])

    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create item_params
    redirect_to action: 'index'
  end

  def item_params
    params.require(:event).permit(:id, :name, :image, :remove_image, :price, :description, :location,:date, :start_date, :end_date, :business_id, :event_category_id)
  end

  def edit

  end

  def update
    @event.update_attributes item_params
    if @event.errors.empty?
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to action: 'index'
  end

  def show

  end

  private
  def find_item
    @event= Event.find_by_id(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
def show_time(event_time)

     tag_class= event_time.time.hour > Time.now.hour ? 'class="col-xs-4 col-sm-2 col-md-1 col-lg-1 time_default"' : 'class="col-xs-4 col-sm-2 col-md-1 time_crossed_out"'
     "<p #{tag_class}>#{event_time.show_hours_minutes}</p>".html_safe
end
end

app/views/events/_form.html.erb
<div class="body_panel panel-default">

  <div class='field form-group'>
    <%= f.label :image, class: 'col-md-2 control-label' %>
    <div class='col-sm-3'>
      <%= f.file_field :image, multiple: false %>
    </div>
  </div>

      <% if @event.image? %>
      <div class='field form-group'>
        <div class='col-md-2 control-label'></div>

        <div class='col-sm-5'>
          <%= f.check_box :remove_image %>
        </div>
      </div>

      <div class="field form-group">
        <div class='col-md-2 control-label'></div>
        <div class='col-sm-10'>
          <%= image_tag(@event.image_url, size: '380', class: "img-thumbnail")%>
        </div>
      </div>

  <% end %>

  <div class="panel-body">
    <%= form_field_text(f, :name) %>
    <div class="row field form-group">
      <%= form_field_row_numeric(f, :price) %>
      <%= form_field_row_date(f, :start_date) %>
      <%= form_field_row_date(f, :end_date) %>
      <%= form_field_row_text(f, :location) %>
    </div>
    <div class='field form-group'>
      <%= f.label :description, class: 'col-md-2 control-label' %>
      <div class='col-sm-10'>
        <%= f.text_area :description, class: 'form-comtrol', rows: 5 %>
      </div>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Save" %>
    </div>
  </div>
</div>

app/views/events/_item.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <div class="well well-sm text-center">
          <%= image_tag(item.image_url, size: '250', class: "img-thumbnail") %>
          <br>
          <br>
          <p><%=t 'duration'  %>: <%= print_date(item.start_date, item.final_date, 'success') %></p>
        </div>
      </div>
      <div class="col-md-8">
        <div class="well">
            <h3><%= link_to item.name, item %></h3>
            <p><%=t 'enterprise' %>: <%= link_to item.enterprise.name, item.enterprise %></p>
          <% unless item.location.blank?  %>
              <p><%=t 'location' %>: <%= item.location %></p>
          <% end %>
          <%unless item.price.blank?  %>
          <p><%=t 'price'  %>: <%= item.price  %> <%=t :currency_main %>    </p>
          <%end%>
          <%unless item.event_times.blank?  %>
          <p> <%=t 'times'  %>:</p>

          <div class="well">
            <% item.event_times.each do |event_time| %>
                <%= show_time(event_time)%>
            <% end %>
            <br>
          </div>
          <%end%>
        </div>
      </div>
    </div>
    <% unless item.description.empty? %>
        <h4><%=t 'description' %>:</h4>
        <div class="well">
          <%= truncate(item.description, :length => 300) %>
          <%= link_to (t 'read more'), item %>
        </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="page-header">
  <h1><%= controller_name.humanize %><small><%= action_name %></small></h1>
</div>

<%= form_for [@event] do |f| %>
    <%= render partial: 'form', locals:{f: f} %>
<% end %>

app/views/events/index.html.erb
<div class="page-header">
  <h1><%=t "#{controller_name}" %>

    <div class="btn-group right" role="group">
      <%= link_to (t 'link_text.today'), events_path(filter_start_date: Date.today) %>
      <%= link_to (t 'link_text.tomorrow'), events_path(filter_start_date: (Date.today+1.day)) %>
      <%= link_to (t 'link_text.all week'), events_path(filter_start_date: Date.today, filter_end_date: (Date.today+7.days)) %>
      <%= link_to (t 'link_text.all time'), events_path %>
    </div>
  </h1>
</div>

<div class="body_panel panel-default">
  <div class="panel-body">


        <% unless @events.blank? %>
            <% @events.each do |event| %>
                <%= render "item", {item: event} %>
      <% end %>
      <% else %>
            <div><%=t 'none_to_show_yet'  %></div>
      <% end %>


  </div>
  <div class="text-center"><%= will_paginate @events, renderer: BootstrapPagination::Rails %></div>
</div>

app/views/events/new.html.erb
<div class="page-header">
  <h1><%= controller_name.humanize %><small><%= action_name %></small></h1>
</div>

<%= form_for [@event] do |f| %>
 <%= render partial: 'form', locals:{f: f} %>
<% end %>

app/views/events/show.html.erb
<% if @event %>
<div class="body_panel panel-default">
  <div class="panel-body">
  
        <div class="col-md-4">
          <div class="panel panel-default text-center">

            <div class="panel-body"><%= image_tag(@event.image_url, size: '250', class: "img-thumbnail") %> </div>

            <div class="panel-footer vert_align_center">
              <br>
              <p><%=t 'duration' %>: <%= @event.duration %></p></div>
          </div>
        </div>


        <div class="col-md-8">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <h2><%= @event.name %></h2>

            </div>
            <div class="panel-body list-group">

              <li class="list-group-item">
                <h4><%= link_to "#{@event.enterprise.name}", enterprise_path(@event.enterprise_id) %></h4></li>
              <li class="list-group-item panel panel-default">
                <div class="panel-heading"><h4><%=t 'description' %>:</h4></div>
                <div class="panel-body"><%= @event.description %></div>
              </li>

              <% unless @event.location.blank?  %>
              <li class="list-group-item"><p><%=t 'location' %>: <%= @event.location %></p></li>
              <%end%>
              <% unless @event.price.blank?  %>
              <li class="list-group-item"><p><%= t 'price' %>: <%= @event.price %> <%=t 'currency_main'  %></p></li>
              <%end%>
              <li class="list-group-item">
                <a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapseTime" aria-expanded="false" aria-controls="collapseTime">
                  <%= t 'Show event times' %>
                </a>

                <div class="collapse" id="collapseTime">
                  <div class="well vert_align_center">
                    <% @event.event_times.order(:time).each do |event_time| %>
                        <%= show_time(event_time)%>
                    <% end %>
                    <br>
                  </div>
                </div>

              </li>


            </div>
          </div>
        </div>

  </div>
</div>
<%end%>