config/routes.rb
Rails.application.routes.draw do
  authenticate do
    get 'admin', to: redirect('admin/enterprise')
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin' 
  end

  get '/:locale' => 'promos#index'
  devise_for :users

  scope "(:locale)", locale: /en|ru|uk/ do
    root 'promos#index'
    resources :enterprises, :events, :promos
    resources :vacancies do
      member do
        post 'send_cv'
      end
    end
  end

end

app/models/promo.rb
class Promo < ActiveRecord::Base

  belongs_to :enterprise

  mount_uploader :image, PromoImageUploader

  validates :name, :starts, :ends, presence: true, allow_blank: false
  validates :name, length: { in: 2...200 }
  validate :start_check, on: :create

  validate :fix_enterprise

  validate :correct_period

  scope :with_includes, -> { includes(:enterprise)}

  self.per_page = 5

  def correct_period
    if starts > ends
      errors.add(:period, 'is not correct: "Starts" date must be lower, or equal "Ends" date')
    end
  end

  def fix_enterprise
    if enterprise_id.nil?
      errors.add(:enterprise, 'must be selected')
    end
  end

  def start_check
    if starts < Date.today
      errors.add(:starts, 'date can\'t be in the past')
    end

  end

end

app/controllers/promos_controller.rb
class PromosController < ApplicationController

  def index
    @promos = Promo.all.with_includes.paginate(:page => params[:page])
    @top_premium = Promo.limit(3).order("RANDOM ()").where(premium: true)
    @bottom_premium = Promo.limit(4).order("RANDOM ()").where(premium: true)

  end

  def show
    @promo = Promo.find_by_id params[:id]
  end

end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_premium_promos.html.erb
<% i = 0 %>
<% enum = 3 %>
<div class="container">
  <% while i < enum %>
      <div class="panel panel-default col-xs-6 col-md-4">
        <% item = elements[i] %>
        <% if item.blank? %>
            <div class="premium_element panel-body">Your Promo can be here!!!</div>
        <% else %>
            <div class="premium_element panel-body">
              <div><%= item.name %></div>
              <!--<br>-->
              <%= link_to promo_path(item.id), {:class => "btn btn-primary", :role => "button"} do %>
                  Read More <span class="glyphicon glyphicon-chevron-right"></span>
              <% end %>
            </div>
        <% end %>
        <% i += 1 %>
      </div>
  <% end %>
</div>

app/views/promos/_promo_element.html.erb
<article class="enterprisespan8">
  <h2>
    <%= link_to promo.name, promo_path(promo.id) %>
  </h2>
  <hr>
  <%= image_tag(promo.image_url, size: '200', class: "img-responsive",) %>
  <div><%=t 'starts' %>: <span><%= promo.starts %></span> <%= t 'ending' %>: <span><%= promo.ends %></span></div>
  <div><%=t 'carried by'  %>: <%= link_to promo.enterprise.name, enterprise_path(promo.enterprise.id) %></div>
  <% unless promo.description.empty? %>
    <%= truncate(promo.description, :length => 650)%>
  <% end %>
</article>
<div class="rmore">
  <%= link_to  promo_path(promo.id), { :class=>"btn btn-primary", :role=>"button" } do %>
     <%=t 'read more' %> <span class="glyphicon glyphicon-chevron-right"></span>
  <% end %>
</div>
<hr>
<br/>

app/views/promos/index.html.erb
<%= render partial: 'premium_promos', locals: {elements: @top_premium} %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <% @promos.each do |item| %>
          <%= render partial: 'promo_element', locals: {promo: item} %>
      <% end %>
    </div>
  </div>
  <div class="text-center"><%= will_paginate @promos, renderer: BootstrapPagination::Rails %></div>
</div>
<%= render partial: 'premium_promos', locals: {elements: @bottom_premium} %>

app/views/promos/show.html.erb
<div class="page-header">
  <h1> <%= t 'promo' %> </h1>
</div>

<div class="body_panel panel-default">
  <div class="panel-body">
    <div class="col-md-4">

      <p><%= image_tag(@promo.image_url, size: '250', class: "img-thumbnail") %> </p>

    </div>
    <div><%= @promo.name %></div>
    <div><%=t 'starts'  %>: <span><%= @promo.starts %></span> <%=t 'ending' %>: <span><%= @promo.ends %></span></div>
    <div><%= %></div>
    <div><%= t 'carried by' %>: <%= link_to @promo.enterprise.name, enterprise_path(@promo.enterprise.id) %></div>
    <div><%= t 'description' %>: <%= @promo.description %></div>
  </div>
</div>