config/routes.rb
Rails.application.routes.draw do
  authenticate do
    get 'admin', to: redirect('admin/enterprise')
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin' 
  end

  get '/:locale' => 'promos#index'
  devise_for :users

  scope "(:locale)", locale: /en|ru|uk/ do
    root 'promos#index'
    resources :enterprises, :events, :promos
    resources :vacancies do
      member do
        post 'send_cv'
      end
    end
  end

end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  def index
    if params[:search]
      @enterprises = Enterprise.search(params[:search]).order("created_at DESC").paginate(:page => params[:page])
    else
      @enterprises = Enterprise.paginate(:page => params[:page]).order("created_at DESC")
    end

  end

  def show
    @enterprise = Enterprise.find_by_id params[:id]
  end

  # def create
  #   @enterprise = Enterprise.new(params[:enterprise])
  #   @enterprise.user_id = current_user.id
  #
  #   if @enterprise.save
  #     redirect_to @enterprise, notice: 'Entry was successfully created.'
  #   else
  #     render :new
  #   end
  # end

end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

app/views/enterprises/_details_sidebar.erb
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">

  <!--
  <div class="well">
    <h4>Categories</h4>
    <div class="row">
      <div class="col-lg-6">
        <ul class="list-unstyled">
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-6">
        <ul class="list-unstyled">
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  -->

  <!-- Side Widget Well -->
  <div class="well">
    <h4><%=t 'Enterprise Info' %></h4>
    <p>
      <span class="glyphicon glyphicon-home"></span> <%= @enterprise.address %>
    </p>
    <p><span class="glyphicon glyphicon-phone-alt"></span> <%= @enterprise.phone %></p>
  </div>

 <div class="well">
   <h4><%=t 'Additional Info' %></h4>
   <div class="row">
     <div class="col-sm-11 col-md-10 col-lg-10">
       <ul class="list-unstyled">
         <li><a href="#"><%=t 'Enterprise Promo' %></a>
         </li>
         <li><a href="#"><%=t 'Enterprise Events' %></a>
         </li>
         <li><a href="#"><%=t 'Enterprise Vacancies' %></a>
         </li>
       </ul>
     </div>
   </div>
 </div>

</div>

app/views/enterprises/_enterprise.html.erb
<article class="enterprisespan8">
  <h2>
    <%= link_to enterprise.name, enterprise_path(enterprise.id) %>
  </h2>
  <hr>
    <%= link_to image_tag(enterprise.picture_url, size: '200', class: "img-responsive",) %>
  <p>
    <span class="glyphicon glyphicon-home"></span> <%= enterprise.address %>
  </p>
  <p><span class="glyphicon glyphicon-phone-alt"></span> <%= enterprise.phone %></p>
  <%=  truncate(enterprise.description, :length => 650)%>
</article>
<div class="rmore">
  <%= link_to  enterprise_path(enterprise.id), { :class=>"btn btn-primary", :role=>"button" } do %>
      <%=t 'read more'  %> <span class="glyphicon glyphicon-chevron-right"></span>
  <% end %>
</div>
<hr>
<br/>

app/views/enterprises/_pager.erb
<!-- Pager -->
<ul class="pager">
  <li class="previous">
    <a href="#">&larr; Older</a>
  </li>
  <li class="next">
    <a href="#">Newer &rarr;</a>
  </li>
</ul>

app/views/enterprises/_sidebar.erb
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">

  <%= form_tag(enterprises_path, :method => "get", id: "search-form") do %>
  <div class="well">
    <h4><%=t 'Enterprise Search' %></h4>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Enterprises" %>
        <span class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
    </div>
  </div>
  <% end %>

  <!--
  <div class="well">
    <h4>Categories</h4>
    <div class="row">
      <div class="col-lg-6">
        <ul class="list-unstyled">
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-6">
        <ul class="list-unstyled">
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  -->

  <!-- Side Widget Well -->
  <div class="well">
    <h4>Some Useful Info </h4>
    <p class="enterprisespan8">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis, unde omnis
      iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa,
      quae ab illo inventore veritatis et quasi architecto beatae vitae</p>
  </div>

</div>

app/views/enterprises/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <% @enterprises.each do |enterprise| %>
          <%= render partial: 'enterprise', locals: {enterprise: enterprise} %>
      <% end %>
    </div>
    <%= render partial: 'sidebar' %>
  </div>
  <div class="text-center"><%= will_paginate @enterprises, renderer: BootstrapPagination::Rails %></div>
</div>

app/views/enterprises/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">

      <article class="enterprisespan8">
        <h2>
          <%= link_to @enterprise.name, enterprise_path(@enterprise.id) %>
        </h2>
        <hr>
        <%= link_to image_tag(@enterprise.picture_url, size: '200', class: "img-responsive",) %>
        <%= @enterprise.description %>
      </article>
      <br/><br/><br/>
    </div>
    <%= render partial: 'details_sidebar' %>
  </div>
</div>